5 ajouter sous système intake
Ultime5528/FRC2024 pull request #16
Opened 2024-01-24 23:45 UTC by UniqueName-Hayder

Description
-----------

Closes #TODO. 

Liste de vérification
---------------------

- Writing conventions :
    - [x] English language
    - [x] File names use lowercase without spaces
    - [x] Class names use PascalCase
    - [x] Functions use camelCase
    - [x] Variable names use snake_case
    - [x] Function and command names start with an action verb (get, set, move, start, stop...)
    - [x] Ports respect the naming convention "subsystem" _ "component type" _ "precision"
    - [x] Properties respect the naming convention
- Command and subsytem safety :
    - [x] Commands and subsystems inherit from SafeCommand and SafeSubsystem
    - [x] No commands or subsytems have a `setName()` method, unless necessary
    - [x] Commands have a `addRequirements()` method that includes all the subsystems they use
- [x] J'ai exécuté tout mon code en simulation.

2024-01-25 02:21 UTC, LaMaudite commented on robot.py
> +        putCommandOnDashboard("Outtake", Drop(self.intake))
Peut-être utiliser le nom de la commande comme nom de commande sur le Dashboard? Par exemple:
putCommandOnDashboard("Drop", Drop(self.intake))

2024-01-27 15:20 UTC, etiennebeaulac commented on robot.py
> +        putCommandOnDashboard("Outtake", Drop(self.intake))
Le premier paramètre est le nom de la subtable. On les utilise comme des catégories pour regrouper les commandes par thème, par sous-système... Donc normalement c'est "Intake" que l'on mettrait. Le 3e paramètre, optionnel ici, est le nom en tant que tel de la commande. Par défaut, il prend le nom de classe (ici, "Drop").

2024-01-30 13:49 UTC, LaMaudite commented on tests/intake_test.py
> +        assert 0 == robot.intake.sim_motor.getVelocity()
Utiliser pytest.approx avec 0.0?

2024-01-31 22:42 UTC, etiennebeaulac requested changes

2024-01-31 22:42 UTC, etiennebeaulac commented on commands/intake/drop.py
> +class Drop(SafeCommand):
Ajouter un Timer qui dépend d'une autoproperty `delay` pour arrêter la commande automatiquement après un certain temps.

2024-01-31 22:42 UTC, etiennebeaulac commented on commands/intake/pickup.py
> +    delay_time = autoproperty(1.00)
`delay = autoproperty(1.0)` est suffisant

2024-01-31 22:42 UTC, etiennebeaulac commented on commands/intake/pickup.py
> +            print(self.intake.hasNote())
Enlever le print

2024-01-31 22:42 UTC, etiennebeaulac commented on subsystems/intake.py
> +            self.sim_motor = SparkMaxSim(self._motor)
Ajouter un underscore devant `sim_motor`, comme les autres attributs "privés".

2024-01-31 22:42 UTC, etiennebeaulac commented on subsystems/intake.py
> +        self.sim_motor.setPosition(self.sim_motor.getPosition() + self._motor.get())
Pourquoi veut-on changer la position du moteur qui active l'intake? On ne le lit jamais, non?

2024-01-31 22:42 UTC, etiennebeaulac commented on tests/intake_test.py
> +
J'ai commenté plus haut d'attendre un délai pour que Drop s'arrête par elle-même. Il faudrait attendre pendant ce délai et vérifier que
1. juste avant la fin du délai, le moteur est activé.
2. après le délai, la commande est unscheduled et le moteur est à l'arrêt.

2024-01-31 22:42 UTC, etiennebeaulac commented on tests/intake_test.py
> +        assert 0 == robot.intake.sim_motor.getVelocity()
Utiliser pytest.approx

2024-02-08 01:07 UTC, etiennebeaulac approved these changes

2024-02-08 01:20 UTC, merged