added shooter subsytem
Ultime5528/FRC2024 pull request #8
Opened 2024-01-18 00:00 UTC by henrimartin456

Description
-----------

Closes #6 . 

Liste de vérification
---------------------

- Writing conventions :
    - [x] English language
    - [x] File names use lowercase without spaces
    - [x] Class names use PascalCase
    - [x] Functions use camelCase
    - [x] Variable names use snake_case
    - [x] Function and command names start with an action verb (get, set, move, start, stop...)
    - [x] Ports respect the naming convention "subsystem" _ "component type" _ "precision"
    - [x] Properties respect the naming convention
- Command and subsytem safety :
    - [x] Commands and subsystems inherit from SafeCommand and SafeSubsystem
    - [x] No commands or subsytems have a `setName()` method, unless necessary
    - [x] Commands have a `addRequirements()` method that includes all the subsystems they use
- [x] J'ai exécuté tout mon code en simulation.

2024-01-24 22:20 UTC, etiennebeaulac requested changes

2024-01-24 22:20 UTC, etiennebeaulac commented on subsystems/shooter.py
> +    shooter_low_speed = autoproperty(0.25)
Enlever "shooter_" devant les propriétés, c'est redondant comme on est déjà dans la classe Shooter.

2024-01-24 22:20 UTC, etiennebeaulac commented on tests/pyfrc_test.py
> -from pyfrc.tests import *
Ce fichier ne devrait pas avoir été supprimé. Il devrait être restauré tel quel.

2024-01-24 22:20 UTC, etiennebeaulac commented on robot.py
> +        # self.drivetrain = Drivetrain(self.getPeriod())
Décommenter le Drivetrain.

2024-01-25 02:26 UTC, LaMaudite commented on subsystems/shooter.py
> +        self.left_motor.set(self.high_speed)
Left and right?

2024-01-25 02:33 UTC, LaMaudite commented on subsystems/shooter.py
> +        self.right_motor_sim.setVelocity(-self.left_motor.get())
pourquoi pas self.right_motor.get() sans le négatif?

2024-01-27 15:22 UTC, etiennebeaulac commented on subsystems/shooter.py
> +        self.right_motor_sim.setVelocity(-self.left_motor.get())
Dans leur init, ils ont choisi de configuer right_motor comme un follower inversé du left_motor. Cela va se passer automatiquement par CAN dans le vrai robot. Ici, il faut le gérer automatiquement.

2024-02-17 17:19 UTC, etiennebeaulac approved these changes

2024-02-17 17:47 UTC, merged